---
- name: Install and configure Apache web server (with nftables + auto SSH port)
  hosts: web
  become: true
  gather_facts: true

  vars:
    site_title: "Hello from Apache (Ansible)"
    site_message: "Apache is installed and serving this page."
    allowed_tcp_ports:
      - 80   # HTTP
      # - 443 # HTTPS (uncomment if/when you enable TLS)

  tasks:
    - name: Install Apache (Debian/Ubuntu)
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
      when: ansible_facts.os_family == "Debian"

    - name: Install Apache (RHEL-family)
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_facts.os_family == "RedHat"

    - name: Deploy index.html to the default web root
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        mode: "0644"
        content: |
          <!doctype html>
          <html>
            <head><meta charset="utf-8"><title>{{ site_title }}</title></head>
            <body style="font-family: Arial, sans-serif;">
              <h1>{{ site_title }}</h1>
              <p>{{ site_message }}</p>
              <hr>
              <p><strong>Host:</strong> {{ inventory_hostname }}</p>
            </body>
          </html>

    - name: Ensure Apache is running and enabled (Debian/Ubuntu)
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      when: ansible_facts.os_family == "Debian"

    - name: Ensure Apache is running and enabled (RHEL-family)
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_facts.os_family == "RedHat"

  
    - name: Check if sshd_config.d exists
      ansible.builtin.stat:
        path: /etc/ssh/sshd_config.d
      register: sshd_config_d_dir

    - name: Find sshd_config.d snippets (if any)
      ansible.builtin.find:
        paths: /etc/ssh/sshd_config.d
        patterns: "*.conf"
        file_type: file
      register: sshd_snippets
      when: sshd_config_d_dir.stat.exists

    - name: Build ordered list of sshd config files to parse
      ansible.builtin.set_fact:
        sshd_config_files: >-
          {{
            ['/etc/ssh/sshd_config']
            + (
                (sshd_snippets.files | map(attribute='path') | list | sort)
                if (sshd_config_d_dir.stat.exists | default(false))
                else []
              )
          }}

    - name: Slurp sshd configuration files
      ansible.builtin.slurp:
        src: "{{ item }}"
      loop: "{{ sshd_config_files }}"
      register: sshd_slurped

    - name: Extract SSH Port directives (last one wins), default 22
      ansible.builtin.set_fact:
        ssh_ports_found: >-
          {{
            (
              sshd_slurped.results
              | map(attribute='content')
              | map('b64decode')
              | map('regex_replace', '(?m)^\\s*#.*$', '')        # strip commented lines
              | map('regex_findall', '(?im)^\\s*Port\\s+(\\d+)\\s*$')
              | list
            ) | flatten
          }}
        ssh_port: "{{ (ssh_ports_found | last) | default('22') | int }}"

    - name: Show detected SSH port (for visibility)
      ansible.builtin.debug:
        msg: "Detected SSH port: {{ ssh_port }} (from {{ sshd_config_files }})"


    - name: Install nftables
      ansible.builtin.package:
        name: nftables
        state: present

    - name: Write nftables ruleset (safe baseline: allow SSH + HTTP)
      ansible.builtin.copy:
        dest: /etc/nftables.conf
        owner: root
        group: root
        mode: "0644"
        content: |
          # Managed by Ansible - nftables ruleset
          flush ruleset

          table inet filter {
            chain input {
              type filter hook input priority 0;
              policy drop;

              # Accept established/related traffic
              ct state established,related accept

              # Allow loopback
              iif "lo" accept

              # Allow ICMP / ICMPv6 (ping, ND, etc.)
              ip protocol icmp accept
              ip6 nexthdr icmpv6 accept

              tcp dport {{ ssh_port }} accept

              # Allow selected TCP ports (HTTP/HTTPS)
              {% for p in allowed_tcp_ports %}
              tcp dport {{ p }} accept
              {% endfor %}
            }

            chain forward {
              type filter hook forward priority 0;
              policy drop;
            }

            chain output {
              type filter hook output priority 0;
              policy accept;
            }
          }
      notify: Validate and apply nftables

    - name: Ensure nftables service is enabled and started
      ansible.builtin.service:
        name: nftables
        state: started
        enabled: true

  handlers:
    - name: Validate and apply nftables
      listen: Validate and apply nftables
      become: true
      block:
        - name: Validate nftables config
          ansible.builtin.command: nft -c -f /etc/nftables.conf
          changed_when: false

        - name: Load nftables ruleset
          ansible.builtin.command: nft -f /etc/nftables.conf
          changed_when: true

        - name: Restart nftables service (ensure persistence on reboot)
          ansible.builtin.service:
            name: nftables
            state: restarted

